### ISSUE TITLE
Velocity proxy console logs often consider as Forge server log

### ISSUE THREAD

**Issue by HowardZHY** [aternosorg/mclogs#104]

**Comment by JulianVennen** [comment]
Do you have an example of that?

**Comment by HowardZHY** [comment]
https://mclo.gs/NONgofV

**Comment by HowardZHY** [comment]
https://mclo.gs/FNjpZkt another wrong example

**Comment by JulianVennen** [comment]
This is a partial log which doesn't contain the velocity startup messages we detect.

If no specific software can be detected our system falls back to the log pattern that matches the most lines.

In this case that's forge because forge and velocity use very similar log patterns and forge is in the list before velocity.

**Comment by HowardZHY** [comment]
> This is a partial log which doesn't contain the velocity startup messages we detect.
> 
> If no specific software can be detected our system falls back to the log pattern that matches the most lines.
> 
> In this case that's forge because forge and velocity use very similar log patterns and forge is in the list before velocity.

well I think it should detect [com.velocitypowered.proxy to decide if it's velocity

**Comment by HowardZHY** [comment]
https://mclo.gs/6JMQuAi a Bungee log as Forge server log

**Comment by JulianVennen** [comment]
You should just share the full log if you expect detections to work correctly.
