### ISSUE TITLE
Ability to hide usernames

### ISSUE THREAD

**Issue by CodingWithAnxiety** [aternosorg/mclogs#126]
Similar to the "hide IPs feature," the ability to hide usernames would be nice.

**Comment by emneo-dev** [comment]
That sounds really hard to implement from what I see in the code, I would even say impossible because there are way too many ways a username could be displayed and too many ways a username can be written as.

I'm not 100% sure of that but I don't think that would be possible except if a username was specifically given to the endpoint then *maybe* it could be hidden.

**Comment by JulianVennen** [comment]
Minecraft usernames are intended to be public, so I don't see any reason to censor them.
